package com.moviereservation.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.*;
import java.util.List;

/**
 * Entity representing a cinema theatre or screen.
 * Defines the physical layout of a screen including the number of rows
 * and seats per row. When a theatre is created, individual Seat records
 * are automatically generated by TheaterService based on these dimensions,
 * ensuring the seat map always reflects the actual screen layout.
 */
@Entity
@Table(name = "theaters")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class Theater {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The name of the theatre displayed in the booking flow and admin panel */
    @Column(nullable = false)
    private String name;

    /** The number of rows of seats in this theatre */
    @Column(nullable = false)
    private Integer totalRows;

    /** The number of seats in each row */
    @Column(nullable = false)
    private Integer seatsPerRow;

    /**
     * All seats in this theatre.
     * JsonIgnore prevents circular serialization when returning theatre data.
     * Cascade ALL ensures seats are deleted when a theatre is deleted.
     */
    @JsonIgnore
    @OneToMany(mappedBy = "theater", cascade = CascadeType.ALL)
    private List<Seat> seats;

    /**
     * All showtimes scheduled in this theatre.
     * JsonIgnore prevents circular serialization when returning theatre data.
     * Cascade ALL ensures showtimes are deleted when a theatre is deleted.
     */
    @JsonIgnore
    @OneToMany(mappedBy = "theater", cascade = CascadeType.ALL)
    private List<Showtime> showtimes;
}